name       : libvirt
version    : 4.7.0
release    : 24
source     :
    - https://libvirt.org/sources/libvirt-4.7.0.tar.xz : 92c279f7321624ac5a37a81f8bbe8c8d2a16781da04c63c99c92d3de035767e4
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : virt
summary    : Library providing a simple virtualization API
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(devmapper)
    - pkgconfig(ext2fs)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libssh)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(OpenEXR)
    - pkgconfig(openssl)
    - pkgconfig(pciaccess)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont)
    - pkgconfig(yajl)
    - dnsmasq
    - ebtables
    - iproute2
    - libpcap-devel
    - parted
rundeps    :
    - ebtables
    - dmidecode
    - dnsmasq
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-check-gnulib-test-getaddrinfo.patch

    %reconfigure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
               --with-init-script=systemd \
               --without-firewalld \
               --without-selinux \
               --with-libvirtd \
               --with-interface
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/libvirt.sysusers $installdir/%libdir%/sysusers.d/libvirt.conf
    # support keyfile backend in libvirt
    install -m 00644 $pkgfiles/50-libvirt.keyrules $installdir/usr/share/polkit-1/rules.d/.
#check      : |
#    %make check
