name       : libvirt
version    : 1.2.16
release    : 1
source     :
    - https://github.com/libvirt/libvirt/archive/v1.2.16.tar.gz : 0047413e6efdf54955903e55416e65df210ab7340449b0040ff5cc1e50caec17
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : libvirt
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnl-route-3.0)
    - pkgconfig(OpenEXR)
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    %make
install    : |
    %make_install
