name       : libvirt
version    : 4.3.0
release    : 18
source     :
    - https://libvirt.org/sources/libvirt-4.3.0.tar.xz : a531e22c8b985ecb2d1223b913fd6ec0f1800e3ebe02351924274885db20c2b7
license    :
    - GPL-2.0
    - LGPL-2.1
component  : virt
summary    : Library providing a simple virtualization API
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - dnsmasq
    - ebtables
    - iproute2
    - libpcap-devel
    - parted
    - pkgconfig(avahi-core)
    - pkgconfig(devmapper)
    - pkgconfig(ext2fs)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libssh)
    - pkgconfig(libxml-2.0)
    - pkgconfig(OpenEXR)
    - pkgconfig(openssl)
    - pkgconfig(pciaccess)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont)
    - pkgconfig(libxslt)
    - pkgconfig(yajl)
rundeps    :
    - ebtables
    - dnsmasq
    - dmidecode
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-check-gnulib-test-getaddrinfo.patch
    %patch -p1 < $pkgfiles/security/cve-2018-3639.patch

    %reconfigure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
               --with-init-script=systemd \
               --without-firewalld \
               --without-selinux \
               --with-libvirtd \
               --with-interface
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/libvirt.sysusers $installdir/%libdir%/sysusers.d/libvirt.conf
    # support keyfile backend in libvirt
    install -m 00644 $pkgfiles/50-libvirt.keyrules $installdir/usr/share/polkit-1/rules.d/.
#check      : |
#    %make check
