name       : libvirt
version    : 3.0.0
release    : 11
source     :
    - https://libvirt.org/sources/libvirt-3.0.0.tar.xz : 9d9d26b70e13b1b2dfde5789ed52fc4528289a37e0f158418e9746263b37175e
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : libvirt
component  : virt
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - dnsmasq
    - ebtables
    - iproute2
    - libpcap-devel
    - parted
    - pkgconfig(avahi-core)
    - pkgconfig(devmapper)
    - pkgconfig(ext2fs)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libssh)
    - pkgconfig(libxml-2.0)
    - pkgconfig(OpenEXR)
    - pkgconfig(openssl)
    - pkgconfig(pciaccess)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont)
    - pkgconfig(libxslt)
    - pkgconfig(yajl)
rundeps    :
    - ebtables
    - dnsmasq
    - dmidecode
setup      : |
    %configure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
               --with-init-script=systemd \
               --without-firewalld \
               --without-selinux \
               --with-libvirtd \
               --with-interface
build      : |
    %make
install    : |
    %make_install
