name       : libvirt
version    : 1.2.16
release    : 4
source     :
    - http://libvirt.org/sources/libvirt-1.2.16.tar.gz : 419bee553442024b9ee8a1fa94023b1189bb52b7c3021fa37d8e4c108490060d
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : libvirt
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnl-route-3.0)
    - pkgconfig(OpenEXR)
    - pkgconfig(pciaccess)
    - pkgconfig(devmapper)
    - ebtables
    - dnsmasq
rundeps    :
    - ebtables
    - dnsmasq
setup      : |
    %configure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
               --with-init-script=systemd \
               --without-firewalld \
               --without-selinux \
               --with-libvirtd \
               --with-interface
build      : |
    %make
install    : |
    %make_install
