name       : libvirt
version    : 1.2.19
release    : 6
source     :
    - http://libvirt.org/sources/libvirt-1.2.19.tar.gz : 282c141f03331d640020c15f81464b27400e0ee307ef4c5190393b021caedd6e
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : libvirt
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - dnsmasq
    - ebtables
    - iproute2-devel
    - libpcap-devel
    - parted
    - pkgconfig(avahi-core)
    - pkgconfig(devmapper)
    - pkgconfig(ext2fs)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libssh)
    - pkgconfig(libxml-2.0)
    - pkgconfig(OpenEXR)
    - pkgconfig(openssl)
    - pkgconfig(pciaccess)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont)
    - pkgconfig(libxslt)
    - pkgconfig(yajl)
rundeps    :
    - ebtables
    - dnsmasq
setup      : |
    %configure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
               --with-init-script=systemd \
               --without-firewalld \
               --without-selinux \
               --with-libvirtd \
               --with-interface
build      : |
    %make
install    : |
    %make_install
