name       : libvirt
version    : 6.3.0
release    : 29
source     :
    - https://libvirt.org/sources/libvirt-6.3.0.tar.xz : 74069438d34082336e99a88146349e21130552b96efc3b7c562f6878127996f5
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : virt
summary    : Library providing a simple virtualization API
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pciaccess)
    - pkgconfig(yajl)
    - dnsmasq
    - ebtables
    - parted
    - python-docutils
rundeps    :
    - ebtables
    - dmidecode
    - dnsmasq
    - parted
setup      : |
    mkdir build
    cd build
    ../%configure ac_cv_path_EBTABLES_PATH=/usr/bin/ebtables \
        --with-init-script=systemd \
        --with-interface \
        --with-libvirtd \
        --without-firewalld \
        --without-selinux
build      : |
    %make -C build
install    : |
    %make_install -C build

    install -Dm00644 $pkgfiles/libvirt.sysusers $installdir/%libdir%/sysusers.d/libvirt.conf
    install -Dm00644 $pkgfiles/libvirt.tmpfiles $installdir/%libdir%/tmpfiles.d/libvirt.conf

    # Support keyfile backend in libvirt
    install -Dm00644 $pkgfiles/50-libvirt.keyrules -t $installdir/usr/share/polkit-1/rules.d

    rm -rf $installdir/usr/share/doc
